# The prefix in front of every message
messages:
  prefix: "<b><gradient:#FFB7D5:#F69AFA:#CAB9E5>BloomVale</gradient></b> <gray>âª¼ "

# Prevent set messages from being logged to the console
# Mainly to prevent spamming the console logs
blocked-messages:
  - "moved too quickly"
  - "Changed text for line"
  - "seconds"

# Cooldown configuration
# Time in seconds
cooldowns:
  heal-seconds: 60
  feed-seconds: 60

back:
  track-teleports: true
  track-deaths: true
  ignore-causes:
    - "SPECTATE"
    - "COMMAND"